package seeds

import (
	bt "github.com/fazaalexander/montirku-be/modules/entity/bengkel"
)

func CreateBengkel() []*bt.Bengkel {
	Bengkels := []*bt.Bengkel{
		{
			UserId:            3,
			Name:              "Bengkel Langgeng Jaya Motor",
			BengkelCategoryId: 1,
			PhoneNumber:       "081234567890",
			StartingPrice:     30000,
			BengkelPhotoUrl:   "https://ibb.co/PgXcJLB",
			AvgRating:         4.5,
			Status:            "Open",
		},
		{
			UserId:            3,
			Name:              "Bengkel Mobil Dasep Ocoy",
			BengkelCategoryId: 2,
			PhoneNumber:       "081234567890",
			StartingPrice:     50000,
			BengkelPhotoUrl:   "https://ibb.co/GHhFkb2",
			AvgRating:         0.0,
			Status:            "Open",
		},
		{
			UserId:            3,
			Name:              "Mulia Motor",
			BengkelCategoryId: 1,
			PhoneNumber:       "081234567890",
			StartingPrice:     30000,
			BengkelPhotoUrl:   "https://ibb.co/PgXcJLB",
			AvgRating:         0.0,
			Status:            "Open",
		},
		{
			UserId:            3,
			Name:              "Anugerah Motor Service",
			BengkelCategoryId: 1,
			PhoneNumber:       "081234567890",
			StartingPrice:     30000,
			BengkelPhotoUrl:   "https://ibb.co/PgXcJLB",
			AvgRating:         0.0,
			Status:            "Closed",
		},
		{
			UserId:            3,
			Name:              "Bengkel Sonny Auto Service",
			BengkelCategoryId: 1,
			PhoneNumber:       "081234567890",
			StartingPrice:     30000,
			BengkelPhotoUrl:   "https://ibb.co/PgXcJLB",
			AvgRating:         0.0,
			Status:            "Closed",
		},
		{
			UserId:            3,
			Name:              "RD Bengkel Mobil & Motor",
			BengkelCategoryId: 3,
			PhoneNumber:       "081234567890",
			StartingPrice:     30000,
			BengkelPhotoUrl:   "https://ibb.co/PgXcJLB",
			AvgRating:         0.0,
			Status:            "Open",
		},
		{
			UserId:            3,
			Name:              "RD Permata Bengkel",
			BengkelCategoryId: 2,
			PhoneNumber:       "081234567890",
			StartingPrice:     50000,
			BengkelPhotoUrl:   "https://ibb.co/PgXcJLB",
			AvgRating:         0.0,
			Status:            "Open",
		},
		{
			UserId:            3,
			Name:              "AHASS Honda Bengkel Tunas Jaya Motor",
			BengkelCategoryId: 1,
			PhoneNumber:       "081234567890",
			StartingPrice:     30000,
			BengkelPhotoUrl:   "https://ibb.co/PgXcJLB",
			AvgRating:         0.0,
			Status:            "Open",
		},
		{
			UserId:            3,
			Name:              "Bengkel mobil maju mapan mandiri",
			BengkelCategoryId: 2,
			PhoneNumber:       "081234567890",
			StartingPrice:     50000,
			BengkelPhotoUrl:   "https://ibb.co/PgXcJLB",
			AvgRating:         0.0,
			Status:            "Open",
		},
		{
			UserId:            3,
			Name:              "Bengkel BEMSPEED",
			BengkelCategoryId: 1,
			PhoneNumber:       "081234567890",
			StartingPrice:     30000,
			BengkelPhotoUrl:   "https://ibb.co/PgXcJLB",
			AvgRating:         0.0,
			Status:            "Open",
		},
		{
			UserId:            3,
			Name:              "Bengkel Dakocan",
			BengkelCategoryId: 2,
			PhoneNumber:       "081234567890",
			StartingPrice:     50000,
			BengkelPhotoUrl:   "https://ibb.co/PgXcJLB",
			AvgRating:         0.0,
			Status:            "Open",
		},
		{
			UserId:            3,
			Name:              "Bengkel Motor Rian",
			BengkelCategoryId: 1,
			PhoneNumber:       "081234567890",
			StartingPrice:     30000,
			BengkelPhotoUrl:   "https://ibb.co/PgXcJLB",
			AvgRating:         0.0,
			Status:            "Open",
		},
		{
			UserId:            3,
			Name:              "Bengkel Mobil spesialis Honda ALMER MOTOR",
			BengkelCategoryId: 2,
			PhoneNumber:       "081234567890",
			StartingPrice:     30000,
			BengkelPhotoUrl:   "https://ibb.co/PgXcJLB",
			AvgRating:         0.0,
			Status:            "Open",
		},
	}

	return Bengkels
}
