name: Deploy to GCP

on:
  push:
    branches:
      - development

env:
  PROJECT_ID: montirku
  REGION: asia-southeast2
  SHORT_SHA: ${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Build and push Docker image
        run: |
          gcloud builds submit --tag gcr.io/${{ env.PROJECT_ID }}/montirku:${{ env.SHORT_SHA }} .

      - name: Deploy Cloud Run service
        run: |
          gcloud run deploy montirku \
            --image gcr.io/${{ env.PROJECT_ID }}/montirku:${{ env.SHORT_SHA }} \
            --region ${{ env.REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --min-instances 1 \
            --max-instances 10 \
            --set-env-vars DB_CONNECTION=mysql,APP_PORT=${{ secrets.APP_PORT }},DB_HOST=${{ secrets.DB_HOST }},DB_PORT=${{ secrets.DB_PORT }},DB_NAME=${{ secrets.DB_NAME }},DB_USERNAME=${{ secrets.DB_USERNAME }},DB_PASSWORD=${{ secrets.DB_PASSWORD }},SMTP_HOST=${{ secrets.SMTP_HOST }},SMTP_PORT=${{ secrets.SMTP_PORT }},SENDER_NAME=${{ secrets.SENDER_NAME }},AUTH_EMAIL=${{ secrets.AUTH_EMAIL }},AUTH_PASSWORD=${{ secrets.AUTH_PASSWORD }},SECRET_KEY=${{ secrets.SECRET_KEY }}
